theme = "kanagawa-dragon"

[editor]
line-number = "relative"
mouse = false
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

